# Generated by Django 2.0.2 on 2018-02-20 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analysis',
                'verbose_name_plural': '17. Анализ(Analysis)',
            },
        ),
        migrations.CreateModel(
            name='ArrowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'arrow_type',
                'verbose_name_plural': '08. Типы стрелок(ArrowType)',
            },
        ),
        migrations.CreateModel(
            name='ArrowWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'arrow_work',
                'verbose_name_plural': '11. Стрелки работ(ArrowWork)',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost_plan', models.FloatField()),
                ('relative_important', models.FloatField()),
            ],
            options={
                'db_table': 'business_process',
                'verbose_name_plural': '03. Бизнес-процессы(BusinessProcess)',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'business_process_group',
                'verbose_name_plural': '02. Группы бизнес-процесов(BusinessProcessGroup)',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcessWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('parent', models.CharField(max_length=32)),
                ('level', models.CharField(max_length=8)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcess')),
            ],
            options={
                'db_table': 'business_process_work',
                'verbose_name_plural': '10. Работы бизнес-процессов(BusinessProcessWork)',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Enterprise.Enterprise')),
            ],
            options={
                'db_table': 'department',
                'verbose_name_plural': '04. Отделы(Department)',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Department')),
            ],
            options={
                'db_table': 'employee',
                'verbose_name_plural': '06. Сотрудники(Employee)',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'factor',
                'verbose_name_plural': '20. Влияющие факторы(Factor)',
            },
        ),
        migrations.CreateModel(
            name='GlossaryArrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrow_description', models.CharField(max_length=64)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ArrowType')),
            ],
            options={
                'db_table': 'glossary_arrow',
                'verbose_name_plural': '09. Глоссарий стрелок(GlossaryArrow)',
            },
        ),
        migrations.CreateModel(
            name='GroupIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'group_indicator',
                'verbose_name_plural': '19. Группы индикаторов(GroupIndicator)',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Factor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GroupIndicator')),
            ],
            options={
                'db_table': 'indicator',
                'verbose_name_plural': '21. Показатели(Indicator)',
            },
        ),
        migrations.CreateModel(
            name='PositionEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'position_employee',
                'verbose_name_plural': '05. Должности сотрудников(PositionEmployee)',
            },
        ),
        migrations.CreateModel(
            name='ProcessExecutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcess')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Employee')),
            ],
            options={
                'db_table': 'process_executor',
                'verbose_name_plural': '07. Исполнители процессов(ProcessExecutor)',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
            options={
                'db_table': 'resource',
                'verbose_name_plural': '15. Ресурсы(Resource)',
            },
        ),
        migrations.CreateModel(
            name='ScaleMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'scale_measure',
                'verbose_name_plural': '13. Шкала измерений(ScaleMeasure)',
            },
        ),
        migrations.CreateModel(
            name='TypeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'type_resource',
                'verbose_name_plural': '12. Типы ресурсов(TypeResource)',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ScaleMeasure')),
            ],
            options={
                'db_table': 'unit_measure',
                'verbose_name_plural': '14. Единицы измерений(UnitMeasure)',
            },
        ),
        migrations.CreateModel(
            name='WorkAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('execution_time', models.CharField(max_length=32)),
                ('relative_importance', models.FloatField()),
                ('relative_cost', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Analysis')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UnitMeasure')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcessWork')),
            ],
            options={
                'db_table': 'work_analysis',
                'verbose_name_plural': '18. Анализ работ(WorkAnalysis)',
            },
        ),
        migrations.CreateModel(
            name='WorkResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.DecimalField(decimal_places=4, max_digits=6)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Resource')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcessWork')),
            ],
            options={
                'db_table': 'work_resource',
                'verbose_name_plural': '16. Ресурсы работ(WorkResource)',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UnitMeasure'),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TypeResource'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UnitMeasure'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PositionEmployee'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='bp_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcessGroup'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Enterprise.Enterprise'),
        ),
        migrations.AddField(
            model_name='arrowwork',
            name='arrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GlossaryArrow'),
        ),
        migrations.AddField(
            model_name='arrowwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcessWork'),
        ),
        migrations.AlterUniqueTogether(
            name='workresource',
            unique_together={('work', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='workanalysis',
            unique_together={('work', 'analysis')},
        ),
        migrations.AlterUniqueTogether(
            name='processexecutor',
            unique_together={('department', 'business_process')},
        ),
        migrations.AlterUniqueTogether(
            name='arrowwork',
            unique_together={('work', 'arrow')},
        ),
    ]
