# Generated by Django 2.0.2 on 2018-02-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost', models.FloatField()),
                ('relative_important', models.FloatField()),
            ],
            options={
                'db_table': 'business_process',
            },
        ),
        migrations.CreateModel(
            name='BusinessProcessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'business_process_group',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'enterprise',
            },
        ),
        migrations.CreateModel(
            name='PositionEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'position_employee',
            },
        ),
        migrations.CreateModel(
            name='ProcessExecutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcess')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Employee')),
            ],
            options={
                'db_table': 'process_executor',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PositionEmployee'),
        ),
        migrations.AddField(
            model_name='department',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Enterprise'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='bp_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.BusinessProcessGroup'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Enterprise'),
        ),
        migrations.AlterUniqueTogether(
            name='processexecutor',
            unique_together={('department', 'business_process')},
        ),
    ]
