# Generated by Django 2.0.2 on 2018-02-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='bp_process',
            field=models.ManyToManyField(through='app.ProcessExecutor', to='app.BusinessProcess'),
        ),
    ]
